### ISSUE TITLE
Szoba jogosultság gondok.

### ISSUE THREAD

**Issue by megbaszaurusz** [Tyloendis/MTTK.hu#15]
Üdv, kedves vezetőség.

 Szeretnék egy általam észrevett hibát jelenteni.

A következő: Csináltam egy alszobát az én szobám alá, majd oda "SZOBA ADMINISZTRÁTORT-T" adtam az illetékesnek, DE én Szoba Tulajdonosa ként nem tudom ki kickelni őt, se elhúzni a szobából a szobámba, egyel feljebb (alszóba ként lett létrehozva a szoba, ahova kapott szoba admint az illető).

Szóval nem nagyon értem így, a rangom is magasabb mint az övé, és egyszerűen nem engedi, akárhogy próbáltam!

Üdvözlettel: megbaszaurusz.

**Comment by Tyloendis** [comment]
Szia!
Mivel sajnos nincsen külön szerveren, illetve szobán belüli húzási jog között különbség a jogosultsági rendszerben, így a szobán belüli húzás kikerült a szoba adminok lehetőségei közül.

Viszont most már piros szobaadminnal elvileg mindenkit ki tudsz rúgni (staffokat leszámítva). Majd teszteld le légyszi, ha lesz időd.
