### ISSUE TITLE
Ismét gondok vannak a jogokkal..

### ISSUE THREAD

**Issue by megbaszaurusz** [Tyloendis/MTTK.hu#16]
Üdv.

Észrevettem egy furcsaságot, ami szerintem nem normális..
Az, hogy a Szoba Adminisztrátor ki tudja kickelni a Szoba Tulajdonosát.

Ha esetleg nem hiba, akkor elnézést.

**Comment by Tyloendis** [comment]
Hiba kijavítva, köszi a jelentést! +10 online óra
